version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - JRUBY_OPTS=-J-Xmx4g
      - DATABASE_URL=mysql2://db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - RPX_API_KEY=0cdf56769f20a2b73a929ac3ba633152
      - RPX_API_REALM=sosol-development
    links:
      - db
