default: &default
  adapter: jdbcmysql
  username: root
  password: password
  host: db

development:
  <<: *default
  database: sosol_development

test:
  <<: *default
  database: sosol_test

production:
  <<: *default
  database: sosol_production
